### ISSUE TITLE
[BUG] Cannot type in notes, issues resizing actor sheets

### ISSUE THREAD

**Issue by kay-hk** [WoD5E-Developers/wod5e#103]
**Describe the bug**
I REALLY want to like this update... but I feel it took a few steps backwards, including styling. It looks less "modern" than it did (even with vampire revised disabled) and I can't say I'm the biggest fan. 

BUT. To the actual bug. 

I am unable to type in notes, equipment, etc... essentially any window that allows for free text input. The button to edit is sort of broken in the middle of the notes.

See attached. 

![image](https://github.com/user-attachments/assets/f60410eb-756c-46fe-866a-b4c4d9321695)

**To Reproduce**
Open any actor sheet and try any input text window. 

**User Information**

- Browser: Firefox, Edge, Chrome (I tried them all)
- FoundryVTT Version: Version 12 Stable - 331 
- World of Darkness 5e system Version: Current (updated to newest)

**Comment by Veilza** [comment]
Do you have any modules enabled, and which ones if any? If any, have you tried with all modules disabled?

**Comment by kay-hk** [comment]
@Veilza This is sadly without any modules. I did think there might be a conflict, but no - base foundy also has this problem for me.

**Comment by Veilza** [comment]
I **did** find a styling issue specifically in Firefox that looks like this is related to. Chrome and Opera were both working fine, but I'm going to implement this fix and see if it resolves it for you as well. Let me know if you still see this issue after the next hotfix.

**Comment by kay-hk** [comment]
That's curious - it appears for me in all browsers, BUT I did initially open foundry in firefox, so maybe some latent setting? 

Thank you! I appreciate you looking into it :)
