### ISSUE TITLE
Feature Request: Humanity Mechanic for Hunter and Werewolf Games

### ISSUE THREAD

**Issue by Henrique2k7** [WoD5E-Developers/wod5e#106]
Feature Request: Humanity Mechanic for Hunter and Werewolf Games

Please describe the basics of the feature you would like to see in the system:
I’d love to see an optional Humanity mechanic added for games like Hunter: The Reckoning and Werewolf: The Apocalypse. It would let players track their characters’ moral standing and psychological state, much like in Vampire: The Masquerade. This could really add depth to gameplay and influence character decisions and interactions, making the story feel even richer and more immersive.

Can this feature be handled by other Foundry modules?
I know some modules might touch on this, but I think a dedicated Humanity mechanic would really bring something special to Hunter and Werewolf games. It would feel more integrated and meaningful.

Additional context:
I just want to say that the recent updates have been fantastic! I really appreciate all the hard work that goes into making this community so special. This feature could really enhance the experience for everyone involved. Thanks for considering it!

**Comment by Veilza** [comment]
Mechanically and from a programming standpoint, there's nothing stopping this from being a feature. I can totally see uses for it!

However, neither Hunter nor Werewolf really support the humanity tracker so a "show humanity tracker" option on those kinds of sheets sounds like it would be confusing, too niche, and on top of that, the "morality tracker" for Werewolf already exists as the Harano/Hauglosk trackers.

I'd have to do some thinking of whether I want to push into homebrew territory like this or leave it up to modules to implement.

Thank you for the suggestion, nonetheless! It's a good one, just not one I'm sure fits having in the base system.

**Comment by Henrique2k7** [comment]
I agree regarding Werewolf (I only mentioned it because if it's being included for Hunter, might as well cover both). There is a rule in the core compendium or player's guide that describes Humanity mechanics for humans. After all, if you’re a vampire hunter willing to do whatever it takes to kill your enemies, you might lose yourself along the way, and I think that's what Paradox was aiming for with that rule. However, they seem to have overlooked it in Hunter, and I believe it would fit nicely since Humanity acts as a moral compass for monsters. A hunter who’s willing to burn down an orphanage to get rid of the vampire living beneath it is just as much of a monster as the vampire itself.

Anyway, I’m glad you think it’s a good idea too! I remember discussing it on Reddit and generally thought it would be nice to suggest since others also found the mechanic interesting. Having it as an actual mechanical feature would help implement this optional rule. :3

**Comment by Veilza** [comment]
I think at the end of the day this is absolutely module territory and would be more intrusive and confusing to add in the system than it justifies it for such niche uses.

So I'll close this issue for now, but definitely don't feel discouraged from submitting other feature requests in the future! I just have to prioritize what belongs in the system and what doesn't.
