### ISSUE TITLE
[LOCALIZATION] Russian localization

### ISSUE THREAD

**Issue by IHappyEndI** [WoD5E-Developers/wod5e#113]
**Is this an existing language, or a new language, that you're requesting a localization update for?**
Existing language

**If an existing language: Is this an incorrect translation, new translations, or both?**
New translations. I spent one session with this translation, the players did not complain, but I will be glad if someone more competent will finalize it

**New or Updated Translations / Localization Files**
Please put your updated translation(s) or localization files below.
[core-ru.json](https://github.com/user-attachments/files/17626770/core-ru.json)
[vampire-ru.json](https://github.com/user-attachments/files/17626771/vampire-ru.json)

**Comment by Veilza** [comment]
Thanks for the localization updates!
