### ISSUE TITLE
[BUG] Werewolf Rites

### ISSUE THREAD

**Issue by maxlovell73** [WoD5E-Developers/wod5e#117]
**Describe the bug**
I cannot find a section on the Werewolf actor  sheet that displays Rites, and there is way to create Rite items. I'm sure this existed when I looked at one of the earlier 4.x versions of the system. Sorry If I'm mistaken.

**To Reproduce**
Create a Werewolf Actor.
Look at the Actor sheet for a Rite section.
Use the Items menu to attempt to create a Rite item.

**Expected behavior**
I would expect the system to allow the creation of a Rite item, with associated dice pool and description fields.
I would expect the character sheet to have a Rite section.

**User Information**

- Browser: Chrome Version 130.0.6723.93 (Official Build) (64-bit)
- FoundryVTT Version: 12 stable 331
- World of Darkness 5e system Version: 5.0.3

**Additional context**
No other details.

**Comment by maxlovell73** [comment]
I looked at an actor sheet I had created in a previous version 4.x of the system, this had a rite in it. When it was converted to 5.0.3 I could still see and edit the Rite in the gifts page of the actor sheet.

**Comment by Veilza** [comment]
Can you send a screenshot of the dialog window that appears when you press "Add Gift"?

Rite appears to be in the list for me:
![image](https://github.com/user-attachments/assets/d1d4bfe7-d630-46be-9364-badfb8bfc3b2)

**Comment by Veilza** [comment]
If this is confusing because the old sheets had a separate "Rites" section - the new version of all the powers pages did away with having unique sections for particular kinds of power categories, just to unify the interface better.

So if that's all the issue is, there's your answer: You should create new rites through the "Add Gift" dialog.

If you're _not_ seeing "Rite" as an option at all, that's an actual issue, though.

**Comment by maxlovell73** [comment]
Thanks, that's the solution. 
Thanks for all your efforts on the WOD System, it looks really good and allowed me to move my game onto foundry from Roll20.
Do you guys have a Patreon page or somewhere to make a donation for your efforts.
Regards,
Max

**Comment by Veilza** [comment]
Glad I could help you out! And extra happy I could make something that you like using to run your games.

I do have both a [Patreon](https://www.patreon.com/Veilza) and [Ko-fi](https://ko-fi.com/veilza), if you're interested in donating - but as I always say, money's never required and I'm just happy to make something that people like. The best way to help me out is report issues you find and enjoy playing with the system. Really it's all I ask for!

**Comment by maxlovell73** [comment]
Well thanks again and I'll pop on patron when I get home this evening.
