### ISSUE TITLE
Clicking on items as GM also changes the view for the player

### ISSUE THREAD

**Issue by SalithTaydan** [WoD5E-Developers/wod5e#126]
I was browsing a PC's sheet as the GM, and I can see him clicking on the different Discipline powers, and then when he went to another 'tab', I clicked on one of his powers and his view was brought back to that 'tab'. This wasn't the behaviour previously, and so I can't 'secretly' view things on any players sheets while they are logged in.

Vampire 5.0.3
Any browser

**Comment by Veilza** [comment]
Because of the way that the power pages are rendered now, this is inevitably going to be the case. There's no plan to "fix" this implementation.
