### ISSUE TITLE
[BUG] Dark Mode linked text

### ISSUE THREAD

**Issue by SalithTaydan** [WoD5E-Developers/wod5e#127]
When you create a linked text to another thing (like a Journal entry pointing to another Journal entry), it is white text on a light grey background when set to dark mode.
When set to a lighter theme, the text changes to black on a light grey background, so it's just the font colour (or linked box) when in dark mode being a bad mix.

v5.0.3
Any browser

**Comment by Veilza** [comment]
Thank you for pointing this out! I'll get it fixed soonish.

**Comment by Veilza** [comment]
Should be fixed in next release
