### ISSUE TITLE
[BUG] Ghoul sheets adding Hunger dice through modifiers

### ISSUE THREAD

**Issue by SalithTaydan** [WoD5E-Developers/wod5e#128]
When using an equipment to attack (e.g. Brass Knuckles), when a specialisation is ticked on in the roll window, it adds a Hunger dice instead of a Vampire dice. Then unticking it removes a Vampire dice, then re-ticking it adds the Vampire dice again (the Hunger dice remains).
The initial toggle is doing thigns incorrectly, then retoggling works as it should, but doesn't undo the incorrect dice.

v5.0.3
All browsers

**Comment by SalithTaydan** [comment]
This might be a problem with weapons added in the older version of the system, as a new weapon I added manually works fine.

**Comment by Veilza** [comment]
Weapons didn't exist in older versions of the system - what type of item do you mean? Custom rolls? Or something else?

It'd help if you were able to provide screenshots.

**Comment by SalithTaydan** [comment]
Sorry, am just getting very confused and got a little mixed up (it's late for me)
Adding a weapon to a ghoul is what's causing it, and we're thinking it's because the ghoul sheet allows rolling of hunger dice when I don't think ghouls ever do roll hunger dice.

**Comment by SalithTaydan** [comment]
![Ghoul Weapon Bug](https://github.com/user-attachments/assets/27f3264a-2e4d-4c02-b900-41eba0035a81)

**Comment by Veilza** [comment]
Ah, I know the issue then. I'll fix it!
