### ISSUE TITLE
[BUG] Rouse Reroll Issue

### ISSUE THREAD

**Issue by zDuffyz** [WoD5E-Developers/wod5e#138]
First, I would like to congratulate you! This new sheet is amazing!!!

Now, I rebember that in the previous sheet if I selected to roll a Rouse Check by the discipline, it would automatically roll 2 rouses and select the highest result (Based on the blood potency), but now its simply not heppening. Is it a bug or you didn't included it yet?

**Comment by Veilza** [comment]
Ah I see the issue. Clicking the discipline roll icon works but the "Cost" button to roll only the rouse button isn't.

I'll get it fixed.

**Comment by Veilza** [comment]
Should be resolved in the next release.
