### ISSUE TITLE
[LOCALIZATION] Russian localization

### ISSUE THREAD

**Issue by IHappyEndI** [WoD5E-Developers/wod5e#140]
**Is this an existing language, or a new language, that you're requesting a localization update for?**
Existing language

**If an existing language: Is this an incorrect translation, new translations, or both?**
Minor adjustments in the translation

**New or Updated Translations / Localization Files**
Please put your updated translation(s) or localization files below.
[core-ru.json](https://github.com/user-attachments/files/17788974/core-ru.json)
[vampire-ru.json](https://github.com/user-attachments/files/17788975/vampire-ru.json)

**Comment by Veilza** [comment]
Thank you for the localization updates! I'll make sure they get included in the next release
