### ISSUE TITLE
[BUG]: Modifiying the Characters Atributes and Skills 

### ISSUE THREAD

**Issue by Broakoli** [WoD5E-Developers/wod5e#147]
**Describe the bug**
Adding a customized attribute or skill (did not try the others) did not work, as it would appear on the sheet but i couldn't allocate points to it.

**To Reproduce**
1. Create PC Sheet 
2. Open the STS Menu to change/customize Attributes or Skills. 

**Expected behavior**
Point allocation and calculation on rolls.

**User Information**
Also, i've went through the code, to see if i could trace the issue, but once it gets stored in the data.log i lose track of were the data is going, or being stored, befored /called to operate. 

- Browser: Not applicable. (Operating directly on Foundry VTT OS)
- FoundryVTT Version: 12.330
- World of Darkness 5e system Version: 5.0.9

**Additional context**
WoD-> Rolled back to version 4.5.3 that did work.

**Comment by Veilza** [comment]
Found the issue. Should be resolved in the next hotfix.

**Comment by Broakoli** [comment]
Thank you Veilza, and thank you for maintaining this System🙏🤙🏻
