### ISSUE TITLE
[BUG] Coterie Sheet 'roll-up'

### ISSUE THREAD

**Issue by SalithTaydan** [WoD5E-Developers/wod5e#148]
Double-clicking the Coterie/Party sheet to 'roll it up' into just it's title bar doesn't work. It instead seems to partially work by rolling up into a smaller window with no details visible.

It is meant to just roll up into the title bar of the window.

v5.0.9

**Comment by Veilza** [comment]
Found the issue. Will be fixed in the next hoxfix.
