### ISSUE TITLE
[BUG] Story Character - Werewolf - Gift deletion

### ISSUE THREAD

**Issue by maxlovell73** [WoD5E-Developers/wod5e#156]
Hi,
I created a story character, type werewolf, with some gifts. When I tried to delete the gifts I could not.

**To Reproduce**
I created a story character, type werewolf.
I added a gift, Ahroun.
I tried to delete the gift using the bin icon.
The gift does not get deleted, no dialog box appears, nothing occurs when the bin icon is selected.

**Expected behavior**
I would expect the gift on the same row as the bin icon to be deleted.

**User Information**

- Browser: 
- Using the stand alone foundry app, version 12 Stable 331
- World of Darkness 5e system Version: 5.0.11

![image](https://github.com/user-attachments/assets/96b5b596-7a1b-453d-88e4-bd8391997d7b)

**Comment by Veilza** [comment]
Will be resolved in the next hotfix
