### ISSUE TITLE
[LOCALIZATION] Enable localization of Werewolf forms abilities

### ISSUE THREAD

**Issue by anclywen** [WoD5E-Developers/wod5e#39]
The abilities of werewolf forms are hard-coded in the template.json file.

https://github.com/WoD5E-Developers/wod5e/blob/1db53e8efbb7e04f665c1ffef0390812e177edaf/template.json#L601-L607

**Comment by Veilza** [comment]
It's on the To-Do List! As it is the Werewolf Forms don't support it but it's definitely coming in the near-future.

**Comment by Veilza** [comment]
Complete - Will be released with Prerelease 2 (Or stable release version 5.0.0)
