### ISSUE TITLE
Despair Dice automation

### ISSUE THREAD

**Issue by zDuffyz** [WoD5E-Developers/wod5e#46]
I did some tests on the Hunter 5th edition sheet and I saw that it has a Despair box that we can mark

I then saw that the group hunter sheet has a Desperation and Danger meter of one to five

Then I tested to see if the desperaiton dice modifier could be automatically aplied to a roll by marking the Despair box on the sheet, with that player sheet added to the Cell Group Sheet

But it didn't work.

So I don't know if this is a bug and it should be adding as an optional modifier tool or its just me being a dreamer.

If you could fix or add this to the system it would be fantastic, and if you find it better I can submit this again but as a "Future Request"

**Comment by Veilza** [comment]
This kind of automation is already planned to be implemented in the near future! I didn't have an issue for it already but it's definitely coming eventually.
