### ISSUE TITLE
[BUG] Blood Surge not working

### ISSUE THREAD

**Issue by Byroks** [WoD5E-Developers/wod5e#54]
**Describe the bug**
When rolling anything and selecting the modifier Blood Surge right before rolling, one of the dice pooles (Normal or Hunger) gets NaN instead of a number which causes the roll to fail. If you choose Blood Surge while selecting the dicepool the roll will work but the bonus from bloodsurge will not be added.

**To Reproduce**
1) Click on any skill -> confirm -> Select Blood Surge -> NaN
![image](https://github.com/user-attachments/assets/4fe512b1-b167-448b-bc43-d1de873d9daa)

2) Click on any skill -> select Blood surge -> confirm
![image](https://github.com/user-attachments/assets/759fa347-5c1b-413a-b140-828dc6fe5842)
![image](https://github.com/user-attachments/assets/35f7c73c-72d4-40af-a03d-a75b377fade5)

**Expected behavior**
The roll should be working with the correct bonus added

**User Information**

- Browser: Firefox
- FoundryVTT Version: v12
- World of Darkness 5e system Version: v5-prerelease-1

**Comment by Veilza** [comment]
Solution found - will be fixed in next prerelease
