### ISSUE TITLE
[BUG] Adding a Boon with + button breaks Vampire sheet

### ISSUE THREAD

**Issue by dmika** [WoD5E-Developers/wod5e#56]
**Describe the bug**
On the Vampire sheet, clicking + to add a Boon makes the Merits/Flaws sections above it disappear, as well as all of the Attributes and Skills on the main tab.

**To Reproduce**
Clicking + next to Boons

**User Information**

- Browser: Chrome
- FoundryVTT Version: latest stable
- World of Darkness 5e system Version: 5.0.0 prerelease

**Comment by Veilza** [comment]
Managed to fix on a separate branch - will be fixed in prerelease 2.
