### ISSUE TITLE
[FEATURE] Automate Oblivion Steins

### ISSUE THREAD

**Issue by Cryslash** [WoD5E-Developers/wod5e#65]
When rolling a rouse check for an Oblivion discipline (the little dice button next to the discipline) a dice result of 1 or 0 should result in a stain. However, this does not happen.

- Browser: Chrome, Edge, Brave
- FoundryVTT Version: 11.315
- World of Darkness 5e system Version: 4.5.3

**Comment by Veilza** [comment]
Hi there! This was supposed to be in the system, but apparently it got lost at some point. Sorry it took so long to get to this, been busy busy!

This feature has been re-added on my development branch and will be fixed with the 5.0 Stable Release.
