### ISSUE TITLE
[FEATURE] System for Spirit sheets for Werewolf 5e

### ISSUE THREAD

**Issue by morlunk** [WoD5E-Developers/wod5e#72]
**Please describe the basics of the feature you would like to see in the system**
Since spirits are a crucial part of a werewolf game, having character sheets for them would add for a more fullfiling play experience.
So basic sistems like their gifts/special abilities, a Power tracker etc would be essential for implementing these sheets.

**Can this feature be handled by other Foundry modules?** (Note, this doesn't disqualify a feature from being considered, but it does lower our priority to get to it)

**Additional context**

**Comment by Veilza** [comment]
Already in Prerelease 4, will be released as part of release 5
