### ISSUE TITLE
[FEATURE] Werewolf - include new pack attributes on the pack sheets

### ISSUE THREAD

**Issue by zDuffyz** [WoD5E-Developers/wod5e#74]
So, Shattered Nation brought new mechanical tools for packs, one of them was the new attributes called: Territory, Community and Spirit. Please include them on the Pack Sheet just like V5 with Chasse, Lean and Portillon.
![Capturar](https://github.com/user-attachments/assets/116fed80-552b-4709-b9a7-62b5e15a74fb)

**Comment by Veilza** [comment]
This is planned! Should be released with the next major update

**Comment by zDuffyz** [comment]
Cool! Do you have an ideia of when it will be released?

**Comment by Veilza** [comment]
End of this month!

**Comment by Veilza** [comment]
Now been added to the Prerelease 5 build. Will be released with Prerelease 5 / officially released with Stable Release 5.0.0
