### ISSUE TITLE
[BUG] Text boxes deleting certain texts when the sheet is updated 

### ISSUE THREAD

**Issue by daviruss** [WoD5E-Developers/wod5e#79]
**Describe the bug**
The text on the Sire, Generation, Concept, Chronicle, Ambition and Desire text boxes is not saved and is deleted when the sheet is updated. This happens in every type of sheet. 

**To Reproduce**
Writing anything on those boxes and simply clicking to lock the sheet

![Foundry_Virtual_Tabletop_sOmua7RO35](https://github.com/user-attachments/assets/8e01e0df-a67e-4489-bb97-007557444826)

Causes all of them to disappear 

![Foundry_Virtual_Tabletop_Jb9FjQI7Rz](https://github.com/user-attachments/assets/1daa63ad-62ce-4cc7-a203-4c67b7c96b2d)

**Expected behavior**
The text should be saved on the sheet even if updated

**User Information**

- Browser: Google Chrome
- FoundryVTT Version: Version 12 Stable - Build 331
- World of Darkness 5e system Version: 5.0.0-prerelease5.1

**Comment by Veilza** [comment]
Known issue, is fixed on my development build. Will be resolved in either a hotfix to the pre-release or during the full release.
