### ISSUE TITLE
[BUG] Attributes Migration

### ISSUE THREAD

**Issue by f-fabner** [WoD5E-Developers/wod5e#93]
**Describe the bug**
"When migrating to version 5.0, all the attributes of all my characters' sheets did not transfer correctly. Regardless of the type of sheet, all attributes ended up being set to 1. The characters' skills were migrated correctly; only the attributes had issues."
![image](https://github.com/user-attachments/assets/45f38228-98ea-454b-8bad-af5f154810bf)

**To Reproduce**
I’m not sure how to reproduce the bug itself, since it occurred during the migration process and doesn’t have a specific trigger to make it appear. The sheets just ended up missing the old attribute information.

**Expected behavior**
It was expected that the sheets would retain their old attributes after the migration, but all of my sheets now simply have every attribute set to 1."

**User Information**

- Browser: Edge
- FoundryVTT Version: 12
- World of Darkness 5e system Version: 5.0.0
![image](https://github.com/user-attachments/assets/52f26dfc-772f-46ec-ba38-bc7af58d6dfc)

**Additional context**
I even made modifications within the system management to world version 5.0.0... but when the sheets were migrated, the attributes still weren’t saved.
![image](https://github.com/user-attachments/assets/66f35c5a-c61b-48cf-af07-d1bec6315005)

**Comment by Veilza** [comment]
Hmmm! Could you send one of the affected actor sheets pre-migration? That'll help me look into this.

**Comment by Veilza** [comment]
Ah I see the problem. I can get this fixed! It loos like the migration isn't running at all and I know why.

**Comment by f-fabner** [comment]
Ok... I restored my world to the previous version using the backup I had made. I’ll be waiting to know how to proceed.

**Comment by Veilza** [comment]
Actually.. My theory about why it's not working from my initial analysis of the module.json isn't correct.

I ran this actor through the migration script and it fixed the attributes just fine.

Could you try to upgrade your world to 5.0.0 again and then, go to the "World of Darkness 5e" settings, scroll down to "World Version," set it to "4.0.0" like pictured below and then restart Foundry? (This can be done just by pressing the Esc key and then pressing "Reload Application")

Let me know if this fixes it.

![image](https://github.com/user-attachments/assets/843240da-d3f2-4ff6-9095-1a8a02fc63ba)

**Comment by f-fabner** [comment]
Unfortunately, it didn’t work...

![image](https://github.com/user-attachments/assets/425a8d41-1076-4be9-abeb-e16fd5deecf1)

I changed the version number to 4.0.0 and reloaded as you instructed, but nothing changed.

**Comment by Veilza** [comment]
That's odd, because I put the exact actor data I gave you into an actor on my end and when I reloaded it migrated all the attributes properly.

Can you try disabling all modules (or trying in a separate world with that actor export, doing the same steps provided in my previous message), and seeing what happens after that?

**Comment by f-fabner** [comment]
I’m going to try reverting to the previous versions (both the world and the system) and will export the same actor again

**Comment by f-fabner** [comment]
After reverting to the previous version… Everything is working as it was:


![image](https://github.com/user-attachments/assets/758ef914-50d4-4c97-ba09-33d63e6dfc97)



Below is the export of the same actor:




[fvtt-Actor-osvald-ken(oc7o)-D58151f2vfhPJcGb.json](https://github.com/user-attachments/files/17607428/fvtt-Actor-osvald-ken.oc7o.-D58151f2vfhPJcGb.json)

**Comment by Veilza** [comment]
I really would recommend disabling all modules and then trying to update to the latest version again.

I tried with the file you just gave me as well and it migrated just fine:

![image](https://github.com/user-attachments/assets/4ed49c0c-6566-4c89-afad-6fe7762c0469)

**Comment by f-fabner** [comment]
I’ll try now... I’m going to disable all the modules and simply update the system and the world. I'll update you soon on what happened...

**Comment by f-fabner** [comment]
After the migration:

![image](https://github.com/user-attachments/assets/4eea460b-a4d3-471b-9f00-8ce3a54293fc)

After setting it to 4.0.0:

![image](https://github.com/user-attachments/assets/47966e8a-7974-44fc-af42-8dee42f37401)

Unfortunately, it didn’t resolve the issue, even after disabling all the modules...

**Comment by Veilza** [comment]
That signals to me that the migration script isn't running for some reason on your end. Did you get the notification, "Migrating actor data..." and did you let the page reload?

**Comment by f-fabner** [comment]
Some blue bars appeared on the screen mentioning character migration... And yes, I did reload afterward.

**Comment by Veilza** [comment]
Either way though, I think the way to fix this is I need you to make a new macro in the macro hotbar, change the "Type" to "Script" and then paste in the below code.

`WOD5E.api.migrateWorld()`

It should look like this:
![image](https://github.com/user-attachments/assets/c577381b-6993-408c-80cd-8e2e12759a48)

Go back to the settings and changing "World Version" back to 4.0.0 (if it isn't already) and then press the "Save" button at the bottom. Then execute that macro.

**Comment by f-fabner** [comment]
This appeared on the screen after clicking the macro:

![image](https://github.com/user-attachments/assets/f1b73238-3d37-4724-86ac-1f3e4e06d0c7)

And even after reloading Foundry, nothing changed."

![image](https://github.com/user-attachments/assets/c1655397-5990-40b5-8394-eaa041db57b1)

**Comment by Veilza** [comment]
Then I... Have legitimately no clue. Everything you've given me shows that it should be migrating properly - it even worked properly on my end when I imported the actor sheet.

If I can think of anything else to try then I'll let you know, but I legitimately don't know why it wouldn't be showing the attributes properly.

**Comment by Veilza** [comment]
Actually I just noticed something... For some reason, you got to the migration code "Fixing <actor>: Migrating specialties data."

No actor _should_ have any specialties data to migrate if you were on 4.0. If you're somehow getting that message I think there might be something wrong with something else in your world that's causing the migration script to stop running.

If you could provide an export of your world maybe I can look further into this that way.

**Comment by f-fabner** [comment]
I went back to the last point where everything was working...

![image](https://github.com/user-attachments/assets/15d5d1a7-7c48-44b1-ac07-f34be590b518)

Could you please explain how to do what you need?
I apologize for my lack of knowledge on what to do... So if you could explain, I will try to carry it out.

**Comment by Veilza** [comment]
Go back to the list of your worlds in the Foundry application and right click on your world:
![image](https://github.com/user-attachments/assets/e071d66c-c321-4f75-b2f9-4cf9439a78b9)

Click on the "Take Backup" button and then confirm that you want to take the backup.

Then, open your Foundry data folder in the Windows file explorer (or equivalent) and go to the "Backups" folder
![image](https://github.com/user-attachments/assets/c42ab902-8cea-4768-b7aa-a081733d6324)

Go to "Worlds"
![image](https://github.com/user-attachments/assets/2a780e77-c1ad-44cd-b3a6-02f7297fddc9)

Go to the folder associated with your world and you should see a list of files like this:
![image](https://github.com/user-attachments/assets/cfff05b5-cadf-4257-848b-96af01789fe2)

Grab the two most recent files (one should be 1kb, one should be much larger, like in my screenshot) and upload them here (Using the "Attach Files" button when you go to add a comment) or somewhere else that I can download them (such as Google Drive)

**Comment by f-fabner** [comment]
So... I found the files... but we have a problem: the JSON file is 907 bytes, while the bak file is 270 MB.

**Comment by Veilza** [comment]
Would you be able to upload both of them to a Google Drive folder or anything like that?

**Comment by f-fabner** [comment]
I just noticed something, my co-GM and I (we have two GMs and four groups of players) tested some other sheets and realized that there are many more sheets with extra problems. Sheets that were vampire SPCs turned into human SPCs, among other issues. We decided to migrate to this latest version and correct everything manually. We’ll take the opportunity to completely reorganize the setting and start the sheets from scratch in the new system to avoid future problems. It’s going to be a lot of work since there are so many actors to redo, but it will be worth it, and it will likely prevent issues in future migrations since they will already have been made in the new system.

One last question before closing the case: after updating everything again, should I keep the version at 4.0.0 or 5.0.0?"

![image](https://github.com/user-attachments/assets/7af5f0e3-4f1b-4223-b506-6b4365502493)


So, I apologize for the trouble and thank you for the help so far. You can mark the bug as resolved and close the issue.

**Comment by Veilza** [comment]
The "World Version" should be automatically updated when the migration script is completed.

The fact that it is not updating, means the migration script is getting stuck somewhere - and I believe that something in your world is causing this to happen, some bad data that's causing it to hang.

If you are going to go through the effort of reorganizing everything, I might strongly recommend you to recreate your actors from scratch if you're noticing other things that are breaking.

I'd be able to troubleshoot for you if I got that world backup - but if not, then I do recommend just remaking all your actor sheets, to prevent that bad data from lingering and causing even more issues in the future.

**Comment by Veilza** [comment]
As an additional note: I don't know if this bad data could be due to a module, something on my part, from the world being made a long time ago, or what. But what I do know is that at least with the example actor you gave me, the migration script ran just fine for that one actor. My current theory is one of your actors has data that's causing the migration script to break, which is why I recommended the above.
